---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: uninstall-agent-chaos
  namespace: default
  annotations:
    probeRef: '[]'
spec:
  # It can be active/stop
  engineState: 'active'
  chaosServiceAccount: uninstall-agent-sa
  experiments:
    - name: uninstall-agent
      spec:
        components:
          env:
            # Helm release name of the agent to remove
            - name: FOLDER
              value: 'flash-agent'

            # namespace the agent release was installed into
            - name: NAMESPACE
              value: 'sock-shop'
