---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: uninstall-application-chaos
  namespace: default
  annotations:
    probeRef: '[]'
spec:
  # It can be active/stop
  engineState: 'active'
  chaosServiceAccount: uninstall-application-sa
  experiments:
    - name: uninstall-application
      spec:
        components:
          env:
            # Helm release name of the app to remove
            - name: FOLDER
              value: 'sock-shop'

            # namespace to tear down (always deleted in full)
            - name: NAMESPACE
              value: 'sock-shop'
